--before migration

BACKUP TO '~/migrationbackup.zip';
ALTER TABLE BOARDGAME ADD PLAYINGTIME INT NOT NULL DEFAULT (0);
ALTER TABLE BOARDGAME ADD MAX_PLAYTIME INT NOT NULL DEFAULT (0);
ALTER TABLE BOARDGAME ADD MIN_PLAYTIME INT NOT NULL DEFAULT (0);
ALTER TABLE USER ADD default_rating INT NOT NULL DEFAULT (4);
ALTER TABLE USER ADD max_games INT NOT NULL DEFAULT (0);
ALTER TABLE USER ADD min_games INT NOT NULL DEFAULT (0);
ALTER TABLE USER ADD default_max_similar_games INT NOT NULL DEFAULT (0);

--after migration

ALTER TABLE BOARDGAME DROP COLUMN CATEGORY;
UPDATE GAME SET BOARDGAME_ID = 18485 WHERE BOARDGAME_ID = 1;
UPDATE GAME SET BOARDGAME_ID = 17405 WHERE BOARDGAME_ID = 3;
UPDATE GAME SET BOARDGAME_ID = 23540 WHERE BOARDGAME_ID = 12;
UPDATE GAME SET BOARDGAME_ID = 253608 WHERE BOARDGAME_ID = 47;
UPDATE GAME SET BOARDGAME_ID = 421 WHERE BOARDGAME_ID = 48;
UPDATE GAME SET BOARDGAME_ID = 3097 WHERE BOARDGAME_ID = 54;
UPDATE GAME SET BOARDGAME_ID = 325191 WHERE BOARDGAME_ID = 55;
UPDATE GAME SET BOARDGAME_ID = 19777 WHERE BOARDGAME_ID = 90;
UPDATE GAME SET BOARDGAME_ID = 196340 WHERE BOARDGAME_ID = 102;
UPDATE GAME SET BOARDGAME_ID = 3076 WHERE BOARDGAME_ID = 108;
UPDATE GAME SET BOARDGAME_ID = 182028 WHERE BOARDGAME_ID = 118;
UPDATE GAME SET BOARDGAME_ID = 214880 WHERE BOARDGAME_ID = 119;
UPDATE GAME SET BOARDGAME_ID = 227143 WHERE BOARDGAME_ID = 150;
UPDATE GAME SET BOARDGAME_ID = 30645 WHERE BOARDGAME_ID = 197;
UPDATE GAME SET BOARDGAME_ID = 272538 WHERE BOARDGAME_ID = 207;
UPDATE GAME SET BOARDGAME_ID = 12750 WHERE BOARDGAME_ID = 213;
UPDATE GAME SET BOARDGAME_ID = 63170 WHERE BOARDGAME_ID = 224;
UPDATE GAME SET BOARDGAME_ID = 282435 WHERE BOARDGAME_ID = 235;
UPDATE GAME SET BOARDGAME_ID = 154809 WHERE BOARDGAME_ID = 261;
UPDATE GAME SET BOARDGAME_ID = 193867 WHERE BOARDGAME_ID = 285;
UPDATE GAME SET BOARDGAME_ID = 124361 WHERE BOARDGAME_ID = 323;
UPDATE GAME SET BOARDGAME_ID = 126163 WHERE BOARDGAME_ID = 354;
DELETE FROM BOARDGAME WHERE ID = 1;
DELETE FROM BOARDGAME WHERE ID = 3;
DELETE FROM BOARDGAME WHERE ID = 12;
DELETE FROM BOARDGAME WHERE ID = 47;
DELETE FROM BOARDGAME WHERE ID = 48;
DELETE FROM BOARDGAME WHERE ID = 54;
DELETE FROM BOARDGAME WHERE ID = 55;
DELETE FROM BOARDGAME WHERE ID = 90;
DELETE FROM BOARDGAME WHERE ID = 102;
DELETE FROM BOARDGAME WHERE ID = 108;
DELETE FROM BOARDGAME WHERE ID = 118;
DELETE FROM BOARDGAME WHERE ID = 119;
DELETE FROM BOARDGAME WHERE ID = 150;
DELETE FROM BOARDGAME WHERE ID = 197;
DELETE FROM BOARDGAME WHERE ID = 207;
DELETE FROM BOARDGAME WHERE ID = 213;
DELETE FROM BOARDGAME WHERE ID = 224;
DELETE FROM BOARDGAME WHERE ID = 235;
DELETE FROM BOARDGAME WHERE ID = 261;
DELETE FROM BOARDGAME WHERE ID = 285;
DELETE FROM BOARDGAME WHERE ID = 323;
DELETE FROM BOARDGAME WHERE ID = 354;