--before migration

BACKUP TO '~/migrationbackup.zip';
ALTER TABLE BOARDGAME ADD PLAYINGTIME INT NOT NULL DEFAULT (0);
ALTER TABLE BOARDGAME ADD MAX_PLAYTIME INT NOT NULL DEFAULT (0);
ALTER TABLE BOARDGAME ADD MIN_PLAYTIME INT NOT NULL DEFAULT (0);

--after migration

ALTER TABLE BOARDGAME DROP COLUMN CATEGORY;
UPDATE GAME SET BOARDGAME_ID = 18485 WHERE BOARDGAME_ID = 1;
UPDATE GAME SET BOARDGAME_ID = 17405 WHERE BOARDGAME_ID = 3;
UPDATE GAME SET BOARDGAME_ID = 23540 WHERE BOARDGAME_ID = 12;
UPDATE GAME SET BOARDGAME_ID = 253608 WHERE BOARDGAME_ID = 47;
UPDATE GAME SET BOARDGAME_ID = 421 WHERE BOARDGAME_ID = 48;
UPDATE GAME SET BOARDGAME_ID = 3097 WHERE BOARDGAME_ID = 54;
UPDATE GAME SET BOARDGAME_ID = 325191 WHERE BOARDGAME_ID = 55;
UPDATE GAME SET BOARDGAME_ID = 19777 WHERE BOARDGAME_ID = 90;
UPDATE GAME SET BOARDGAME_ID = 196340 WHERE BOARDGAME_ID = 102;
UPDATE GAME SET BOARDGAME_ID = 3076 WHERE BOARDGAME_ID = 108;
UPDATE GAME SET BOARDGAME_ID = 182028 WHERE BOARDGAME_ID = 118;
UPDATE GAME SET BOARDGAME_ID = 214880 WHERE BOARDGAME_ID = 119;
UPDATE GAME SET BOARDGAME_ID = 227143 WHERE BOARDGAME_ID = 150;
DELETE FROM BOARDGAME WHERE ID = 1
DELETE FROM BOARDGAME WHERE ID = 3
DELETE FROM BOARDGAME WHERE ID = 12
DELETE FROM BOARDGAME WHERE ID = 47
DELETE FROM BOARDGAME WHERE ID = 48
DELETE FROM BOARDGAME WHERE ID = 54
DELETE FROM BOARDGAME WHERE ID = 55
DELETE FROM BOARDGAME WHERE ID = 90
DELETE FROM BOARDGAME WHERE ID = 102
DELETE FROM BOARDGAME WHERE ID = 108
DELETE FROM BOARDGAME WHERE ID = 118
DELETE FROM BOARDGAME WHERE ID = 119
DELETE FROM BOARDGAME WHERE ID = 150